2025-10-17T15:03:05: PM2 log: ===============================================================================
2025-10-17T15:03:05: PM2 log: --- New PM2 Daemon started ----------------------------------------------------
2025-10-17T15:03:05: PM2 log: Time                 : Fri Oct 17 2025 15:03:05 GMT-0300 (Paraguay Standard Time)
2025-10-17T15:03:05: PM2 log: PM2 version          : 6.0.13
2025-10-17T15:03:05: PM2 log: Node.js version      : 24.9.0
2025-10-17T15:03:05: PM2 log: Current arch         : arm64
2025-10-17T15:03:05: PM2 log: PM2 home             : /data/data/com.termux/files/home/.pm2
2025-10-17T15:03:05: PM2 log: PM2 PID file         : /data/data/com.termux/files/home/.pm2/pm2.pid
2025-10-17T15:03:05: PM2 log: RPC socket file      : /data/data/com.termux/files/home/.pm2/rpc.sock
2025-10-17T15:03:05: PM2 log: BUS socket file      : /data/data/com.termux/files/home/.pm2/pub.sock
2025-10-17T15:03:05: PM2 log: Application log path : /data/data/com.termux/files/home/.pm2/logs
2025-10-17T15:03:05: PM2 log: Worker Interval      : 30000
2025-10-17T15:03:05: PM2 log: Process dump file    : /data/data/com.termux/files/home/.pm2/dump.pm2
2025-10-17T15:03:05: PM2 log: Concurrent actions   : 2
2025-10-17T15:03:05: PM2 log: SIGTERM timeout      : 1600
2025-10-17T15:03:05: PM2 log: Runtime Binary       : /data/data/com.termux/files/usr/bin/node
2025-10-17T15:03:05: PM2 log: ===============================================================================
2025-10-17T15:03:05: PM2 log: App [deepseek-api:0] starting in -fork mode-
2025-10-17T15:03:05: PM2 log: App [deepseek-api:0] online
2025-10-17T15:03:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:03:05: PM2 error: Error while calling "getconf CLK_TCK" Error: Command failed: getconf CLK_TCK
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at genericNodeError (node:internal/errors:985:15)
    at wrappedFn (node:internal/errors:539:14)
    at ChildProcess.exithandler (node:child_process:417:12)
    at ChildProcess.emit (node:events:508:28)
    at ChildProcess.emit (node:domain:552:15)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:508:28)
    at Socket.emit (node:domain:552:15)
    at Pipe.<anonymous> (node:net:346:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'getconf CLK_TCK'
}
2025-10-17T15:03:05: PM2 error: Error while calling "getconf PAGESIZE" Error: Command failed: getconf PAGESIZE
/data/data/com.termux/files/usr/bin/sh: 1: getconf: not found

    at genericNodeError (node:internal/errors:985:15)
    at wrappedFn (node:internal/errors:539:14)
    at ChildProcess.exithandler (node:child_process:417:12)
    at ChildProcess.emit (node:events:508:28)
    at ChildProcess.emit (node:domain:552:15)
    at maybeClose (node:internal/child_process:1101:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:508:28)
    at Socket.emit (node:domain:552:15)
    at Pipe.<anonymous> (node:net:346:12) {
  code: 127,
  killed: false,
  signal: null,
  cmd: 'getconf PAGESIZE'
}
2025-10-17T15:03:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:03:15: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:03:29: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:03:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:04:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:04:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:42: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:53: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:54: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:55: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:56: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:57: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:58: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:05:59: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:00: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:01: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:02: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:03: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:04: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:06: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:07: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:08: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:10: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:06:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:07:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:07:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:07:09: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:07:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:08:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:08:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:09:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:09:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:10:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:10:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:11:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:11:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:12:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:12:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:13:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:13:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:14:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:14:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:15:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:15:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:16:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:16:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:17:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:17:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:18:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:18:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:19:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:19:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:20:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:20:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:21:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:21:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:22:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:22:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:23:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:23:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:24:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:24:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:25:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:25:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:26:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:26:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:27:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:27:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:28:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:28:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:29:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:29:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:30:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:30:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:31:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:31:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:32:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:32:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:33:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:33:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:34:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:34:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:35:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:35:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:36:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:36:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:37:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:37:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:38:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:38:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:39:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:39:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:40:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:40:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:41:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:41:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:42:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:42:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:43:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:43:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:44:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:44:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:45:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:45:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:46:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:46:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:47:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:47:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:48:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:48:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:49:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:49:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:50:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:50:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:51:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:51:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:52:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:52:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:53:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:53:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:54:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:54:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:55:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:55:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:56:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:56:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:57:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:57:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:58:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:58:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:59:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T15:59:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:00:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:00:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:01:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:01:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:02:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:02:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:03:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:03:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:04:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:04:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:05:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:05:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:06:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:06:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:07:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:07:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:08:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:08:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:09:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:09:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:10:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:10:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:11:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:11:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:12:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:12:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:13:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:13:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:14:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:14:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:15:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:15:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:16:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:16:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:17:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:17:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:18:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:18:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:19:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:19:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:20:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:20:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:21:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:21:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:22:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:22:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:23:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:23:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:24:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:24:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:25:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:25:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:26:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:26:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:27:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:27:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:28:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:28:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:29:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:29:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:30:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:30:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:31:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:31:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:32:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:32:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:33:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:33:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:34:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:34:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:35:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:35:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:36:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:36:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:37:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:37:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:38:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:38:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:39:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:39:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:40:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:40:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:41:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:41:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:42:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:42:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:43:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:43:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:44:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:44:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:45:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:45:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:46:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:46:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:47:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:47:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:48:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:48:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:49:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:49:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:50:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:50:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:51:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:51:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:52:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:52:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:53:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:53:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:54:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:54:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:55:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:55:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:56:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:56:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:57:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:57:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:58:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:58:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:59:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T16:59:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:00:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:00:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:01:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:01:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:02:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:02:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:03:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:03:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:04:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:04:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:05:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:05:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:06:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:06:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:07:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:07:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:08:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:08:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:09:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:09:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:10:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:10:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:11:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:11:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:12:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:12:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:13:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:13:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:14:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:14:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:15:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:15:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:16:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:16:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:17:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:17:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:18:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:18:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:19:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:19:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:20:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:20:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:21:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:21:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:22:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:22:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:23:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:23:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:24:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:24:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:25:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:25:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:26:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:26:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:27:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:27:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:28:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:28:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:29:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:29:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:30:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:30:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:31:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:31:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:32:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:32:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:33:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:33:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:34:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:34:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:35:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:35:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:36:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:36:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:37:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:37:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:38:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:38:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:39:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:39:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:40:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:40:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:41:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:41:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:42:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:42:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:43:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:43:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:44:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:44:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:45:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:45:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:46:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:46:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:47:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:47:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:48:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:48:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:49:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:49:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:50:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:50:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:51:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:51:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:52:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:52:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:53:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:53:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:54:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:54:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:55:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:55:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:56:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:56:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:57:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:57:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:58:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:58:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:59:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T17:59:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:00:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:00:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:01:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:01:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:02:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:02:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:03:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:03:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:04:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:04:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:05:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:05:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:06:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:06:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:07:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:07:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:08:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:08:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:09:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:09:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:10:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:10:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:11:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:11:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:12:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:12:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:13:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:13:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:14:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:14:35: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
2025-10-17T18:15:05: PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value
